// ── Wedding info ──────────────────────────────────────────────────────────────
const WEDDING = {
  bride: 'May',
  groom: 'Jun Yu',
  dateDisplay: '26 Sep 2026',
  year: 2026,
  month: 8,
  day: 26, // month is 0-indexed (8 = September)
};

// ── Schedule phases ───────────────────────────────────────────────────────────
const phases = [
  { name: 'Getting Ready', range: '3:00 AM – 9:30 AM' },
  { name: 'Tea Ceremony', range: '9:45 AM – 11:30 AM' },
  { name: 'Ceremony', range: '12:00 PM – 1:00 PM' },
  { name: 'Reception', range: '1:00 PM – 3:00 PM' },
];

// ── Schedule events ───────────────────────────────────────────────────────────
// type: 'event' = something happening  |  'task' = someone needs to act
const events = [
  // Getting Ready
  {
    phase: 0,
    type: 'event',
    time: '3:00 AM',
    mins: 180,
    title: "May's makeup begins",
    sub: 'Carlton Hotel · Karyn - 9639 8128 · end ~6.30 AM',
  },
  {
    phase: 0,
    type: 'event',
    time: '5:00 AM',
    mins: 300,
    title: "Jy's makeup & styling begins",
    sub: 'Carlton Hotel · Anna - 8925 8028 · end ~5.30 AM',
  },
  {
    phase: 0,
    type: 'task',
    time: '5:00 AM',
    mins: 300,
    title: "Call May's mum — confirm ETA",
    assignee: 'Yong Han',
  },
  {
    phase: 0,
    type: 'task',
    time: '5:00 AM',
    mins: 300,
    title: 'Order breakfast',
    assignee: 'Siew Hwee',
  },
  {
    phase: 0,
    type: 'event',
    time: '6:00 AM',
    mins: 360,
    title: 'Eat breakfast',
    sub: '',
  },
  {
    phase: 0,
    type: 'event',
    time: '5:45 AM',
    mins: 345,
    title: "May's mum makeup begins",
    sub: 'Carlton Hotel · Anna - 8925 8028 · end ~7.00 AM',
  },
  {
    phase: 0,
    type: 'task',
    time: '6:30 AM',
    mins: 390,
    title: 'Prepare items to bring to venue',
    assignee: 'Wei Jie',
    details:
      "• Wedding bands x 2\n• Bridal bouquet\n• JY's parents corsages\n• Hotel key card\n• Vows cards\n• Polaroid\n• Thumbdrive\n• Angbaos for venue people\n• Venue decorations\n• Misc items\n\nIf anything is missing, flag it to Junyu or May.",
  },
  {
    phase: 0,
    type: 'event',
    time: '6:00 AM',
    mins: 360,
    title: 'Photographer arrives at hotel',
    sub: 'Yan Cong - 9159 2973',
  },
  {
    phase: 0,
    type: 'task',
    time: '7:00 AM',
    mins: 420,
    title: "Pass corsages to May's parents",
    assignee: 'Yong Han',
  },
  {
    phase: 0,
    type: 'task',
    time: '7:00 AM',
    mins: 420,
    title: 'Make sure JY wears his corsage',
    assignee: 'Wei Jie',
  },
  {
    phase: 0,
    type: 'event',
    time: '7:15 AM',
    mins: 435,
    title: 'Veiling by parents',
    sub: '',
  },
  {
    phase: 0,
    type: 'event',
    time: '7:45 AM',
    mins: 465,
    title: 'Jy picks up May',
    sub: '',
  },
  {
    phase: 0,
    type: 'task',
    time: '8:00 AM',
    mins: 480,
    title: 'Reach Esplanade',
    assignee: 'Everyone',
  },
  {
    phase: 0,
    type: 'event',
    time: '8:15 AM',
    mins: 495,
    title: 'Start Photoshoot',
    sub: 'Esplanade',
  },
  {
    phase: 0,
    type: 'event',
    time: '8:45 AM',
    mins: 525,
    title: "Jy's mum makeup begins",
    sub: "Junyu's house · Anna - 8925 8028 · end 10.00 AM",
  },
  {
    phase: 0,
    type: 'event',
    time: '9:15 AM',
    mins: 555,
    title: 'End Photoshoot',
    sub: 'Travel to Secret Haven',
  },
  // Tea Ceremony
  {
    phase: 1,
    type: 'event',
    time: '9:45 AM',
    mins: 585,
    title: 'Arrive at Secret Haven',
    sub: 'Couple + full bridal party',
  },
  {
    phase: 1,
    type: 'event',
    time: '10:00 AM',
    mins: 600,
    title: "May's second makeup begins",
    sub: 'Style change · 1h',
  },
  // Each 10 AM job is its own card so it can carry its own `details` instructions.
  // `duty` pulls the people from `roles`, so the names stay in sync with the cards.
  {
    phase: 1,
    type: 'task',
    time: '10:00 AM',
    mins: 600,
    title: 'Prepare for tea ceremony',
    duty: 'Prepare for tea ceremony',
    details: 'Figure out the tea pouring / angbao flow before the couple arrives.',
  },
  {
    phase: 1,
    type: 'task',
    time: '10:00 AM',
    mins: 600,
    title: 'Table cards placement',
    duty: 'Table cards placement',
    details: 'Check that the table seats are assigned correctly.',
  },
  {
    phase: 1,
    type: 'task',
    time: '10:00 AM',
    mins: 600,
    title: 'Reception table decorations',
    duty: 'Reception table decorations',
    details: 'Set up:\n• Photos\n• Seat QR code\n• Photobooth',
  },
  {
    phase: 1,
    type: 'task',
    time: '10:00 AM',
    mins: 600,
    title: 'Venue decorations',
    duty: 'Venue decorations',
  },
  {
    phase: 1,
    type: 'task',
    time: '10:00 AM',
    mins: 600,
    title: "Pass corsages to JY's parents",
    duty: "Pass corsages to JY's parents",
  },
  {
    phase: 1,
    type: 'task',
    time: '10:00 AM',
    mins: 600,
    title: 'Set up music and slides',
    assignee: 'Gin Ling',
  },
  {
    phase: 1,
    type: 'event',
    time: '11:00 AM',
    mins: 660,
    title: "Tea ceremony — Jy's family",
    sub: 'Couple serves tea',
    duty: 'Handle tea ceremony',
    details: 'Serving order:',
    detailsTable: [
      ['Ong Cheong Hong & Chen Dao Fang', "JY's parents"],
      ['?', "JY's 大伯母"],
      ['?', "JY's 二伯伯 和伯母"],
      ['Yap Siew Tin', "JY's 大姑姑"],
      ['Lim Siew Miu & Lim Chwee Khoon', "JY's 小姑姑 & 姑丈"],
      ['陈一猛 (Cheng Yi Meng)', "JY's 舅舅"],
    ],
  },
  {
    phase: 1,
    type: 'event',
    time: '11:30 AM',
    mins: 690,
    title: "Tea ceremony — May's family",
    sub: 'Couple serves tea',
    duty: 'Handle tea ceremony',
    details: 'Serving order:',
    detailsTable: [
      ['Maung Myint Lwin & Daw Cho Cho Aung', "May's parents"],
      ['U Aung Min & Daw Tin Tin Win', "May's grandparents"],
      ['Than Htay & Khin Khin Aye', "May's grand uncle & wife"],
      ['Kyu Kyu', "May's maternal uncle's wife"],
      ['Moe Moe Aung & Soe Myint', "May's maternal aunt & husband"],
      ['Pho Ti & Li Na', "May's paternal cousin & wife"],
      ['Aye Aye Min & U San Win', '?'],
    ],
  },
  {
    phase: 1,
    type: 'task',
    time: '12:00 PM',
    mins: 690,
    title: 'Pass all angbaos from tea ceremony to Weijie',
    assignee: 'Gin Ling',
  },
  // Ceremony
  {
    phase: 2,
    type: 'event',
    time: '12:00 PM',
    mins: 720,
    title: 'Guests arrive',
    sub: 'Bridal party on welcome duty at entrance',
    duty: 'Handle reception',
    detailsLink: {
      label: 'Check guests in',
      url: 'https://docs.google.com/spreadsheets/d/1ynjh4GpLGLPZjHzHRXxhkQpvhFdj_NqHdMmzXt3Qavs/edit?usp=sharing',
    },
  },
  {
    phase: 2,
    type: 'event',
    time: '12:00 PM',
    mins: 720,
    title: 'May changes to white gown',
    sub: '',
  },
  {
    phase: 2,
    type: 'task',
    time: '12:15 PM',
    mins: 735,
    title: 'Receive solemniser',
    assignee: 'Zach',
  },
  {
    phase: 2,
    type: 'task',
    time: '12:00 PM',
    mins: 720,
    title: 'Oversee solemnisation table set up',
    assignee: 'Ivy',
    details: '• Rings\n• Vow cards\n• Polaroid',
  },
  {
    phase: 2,
    type: 'event',
    time: '12:20 PM',
    mins: 740,
    title: 'Start seating guests',
    sub: '',
  },
  {
    phase: 2,
    type: 'event',
    time: '12:25 PM',
    mins: 745,
    title: 'Registration closes',
    sub: '',
  },
  {
    phase: 2,
    type: 'event',
    time: '12:30 PM',
    mins: 750,
    title: 'Ceremony begins',
    sub: '',
  },
  {
    phase: 2,
    type: 'task',
    time: '12:25 PM',
    mins: 745,
    title: 'Pass all angbaos from reception to Weijie',
    assignee: 'Siew Hwee',
  },
  {
    phase: 2,
    type: 'event',
    time: '12:35 PM',
    mins: 755,
    title: 'Couple walks in',
    sub: '',
  },
  {
    phase: 2,
    type: 'event',
    time: '12:40 PM',
    mins: 760,
    title: 'Solemnisation',
    sub: '',
  },
  // Reception
  {
    phase: 3,
    type: 'event',
    time: '1:00 PM',
    mins: 780,
    title: 'Serve first dish',
    sub: '',
  },
  {
    phase: 3,
    type: 'task',
    time: '1:25 PM',
    mins: 805,
    title: 'Start setting up Game 1',
    assignee: 'Darren',
  },
  {
    phase: 3,
    type: 'event',
    time: '1:20 PM',
    mins: 800,
    title: 'Serve second dish',
    sub: '',
  },
  {
    phase: 3,
    type: 'event',
    time: '1:30 PM',
    mins: 810,
    title: 'Game 1',
    sub: 'Shoes game',
  },
  {
    phase: 3,
    type: 'event',
    time: '2:00 PM',
    mins: 840,
    title: 'Serve main dish',
    sub: '',
  },
  {
    phase: 3,
    type: 'task',
    time: '2:15 PM',
    mins: 855,
    title: 'Prep Kahoot game',
    assignee: 'Richie',
  },
  {
    phase: 3,
    type: 'event',
    time: '2:20 PM',
    mins: 860,
    title: 'Game 2',
    sub: 'Kahoot',
  },
  {
    phase: 3,
    type: 'event',
    time: '2:35 PM',
    mins: 875,
    title: 'Serve dessert',
    sub: '',
  },
  {
    phase: 3,
    type: 'event',
    time: '2:35 PM',
    mins: 875,
    title: 'Pre-wedding video',
    sub: '',
  },
  {
    phase: 3,
    type: 'event',
    time: '2:45 PM',
    mins: 885,
    title: 'Couple speech',
    sub: '',
  },
  {
    phase: 3,
    type: 'event',
    time: '2:55 PM',
    mins: 895,
    title: 'Closing',
    sub: 'Final photo · Farewell',
  },
];

// ── Roles ─────────────────────────────────────────────────────────────────────
// All-day duties with no fixed slot. Duties tied to a moment instead live on the
// relevant event via its `duty` field, so their time comes from the schedule.
const dutyTimes = {
  "Bride's person": 'All day',
  "Handle May's Instagram": 'All day',
  'Our DJI IC': 'All day',
  'Guard angbaos with your life': 'All day',
  'Yap yap yap': 'All day',
};

// `title` used only for special duties (Emcee, Angbao keeper/driver). Fill names later.
const roles = {
  bride: [
    {
      id: 'B1',
      name: 'Gin Ling',
      phone: '8448 0040',
      title: '',
      tasks: [
        'Reach Esplanade',
        'Prepare for tea ceremony',
        'Venue decorations',
        'Set up music and slides',
        'Handle tea ceremony',
        'Handle reception',
        'Pass all angbaos from tea ceremony to Weijie',
      ],
    },
    {
      id: 'B2',
      name: 'Yong Han',
      phone: '9641 0621',
      title: '',
      tasks: [
        "Call May's mum — confirm ETA",
        "Pass corsages to May's parents",
        'Reach Esplanade',
        'Reception table decorations',
        "Bride's person",
      ],
    },
    {
      id: 'B3',
      name: 'Xue Yi',
      phone: '9099 2971',
      title: '',
      tasks: [
        "Handle May's Instagram",
        'Reach Esplanade',
        'Prepare for tea ceremony',
        'Venue decorations',
        'Handle tea ceremony',
      ],
    },
    {
      id: 'B4',
      name: 'Ivy',
      phone: '8595 2788',
      title: '',
      tasks: [
        'Our DJI IC',
        'Reach Esplanade',
        'Prepare for tea ceremony',
        'Venue decorations',
        'Handle tea ceremony',
        'Oversee solemnisation table set up',
      ],
    },
    {
      id: 'B5',
      name: 'Siew Hwee',
      phone: '8388 2861',
      title: '',
      tasks: [
        'Order breakfast',
        'Reach Esplanade',
        "Pass corsages to JY's parents",
        'Reception table decorations',
        'Handle reception',
        'Pass all angbaos from reception to Weijie',
      ],
    },
  ],
  groom: [
    {
      id: 'G1',
      name: 'Shijun',
      phone: '9731 6543',
      title: 'Main PIC',
      tasks: ['Reach Esplanade', 'Table cards placement', 'Venue decorations'],
    },
    {
      id: 'G2',
      name: 'Darren',
      phone: '9727 7684',
      title: '',
      tasks: [
        'Reach Esplanade',
        'Table cards placement',
        'Venue decorations',
        'Handle reception',
        'Start setting up Game 1',
      ],
    },
    {
      id: 'G3',
      name: 'Richie',
      phone: '8369 1997',
      title: '',
      tasks: [
        'Reach Esplanade',
        'Table cards placement',
        'Venue decorations',
        'Handle reception',
        'Prep Kahoot game',
      ],
    },
    {
      id: 'G4',
      name: 'Wei Jie',
      phone: '9734 0785',
      title: 'Angbao keeper / Chauffeur',
      tasks: [
        'Prepare items to bring to venue',
        'Make sure JY wears his corsage',
        'Reach Esplanade',
        'Guard angbaos with your life',
      ],
    },
    {
      id: 'G5',
      name: 'Zach',
      phone: '8807 8344',
      title: 'Emcee',
      tasks: [
        'Reach Esplanade',
        'Handle tea ceremony',
        'Receive solemniser',
        'Yap yap yap',
      ],
    },
  ],
};

// ── Contacts ──────────────────────────────────────────────────────────────────
// iconType: 'coordinator' | 'camera' | 'makeup' | 'person'
const contacts = [
  {
    name: 'Wedding / Venue coordinator',
    role: 'Ewis · The Secret Haven',
    phone: '96408205',
    iconType: 'coordinator',
  },
  { name: 'Photographer', role: 'Yan Cong', phone: '91592973', iconType: 'camera' },
  { name: 'Bride makeup', role: 'Karyn', phone: '96398128', iconType: 'makeup' },
  { name: "Mum's makeup", role: 'Anna', phone: '89258028', iconType: 'makeup' },
];

// ── Locations ─────────────────────────────────────────────────────────────────
const locations = [
  {
    tag: 'Getting Ready',
    name: 'Carlton Hotel Singapore',
    address: '76 Bras Basah Road, Singapore 189558',
    mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Carlton%20Hotel%20Singapore',
  },
  {
    tag: 'Wedding',
    name: 'The Secret Haven',
    address: '31 Mount Sophia, Singapore 228480',
    mapsUrl: 'https://www.google.com/maps/search/?api=1&query=The%20Secret%20Haven%20Singapore',
  },
  {
    tag: 'Photoshoot',
    name: 'Esplanade',
    address: '1 Esplanade Drive, Singapore 038981',
    mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Esplanade%20Singapore',
  },
];

// ── Key info at a glance ──────────────────────────────────────────────────────
const glance = [
  { icon: '🪑', label: 'Be seated by', value: '12:20 PM' },
  { icon: '💍', label: 'Solemnisation', value: '12:35 PM' },
  { icon: '🍽️', label: 'Lunch', value: '1:00 PM' },
  { icon: '🎉', label: 'Reception ends', value: '3:00 PM' },
  { icon: '🧧', label: 'Angbao', value: 'Give to Wei Jie' },
  { icon: '🚻', label: 'Toilet', value: 'Left of the screen' },
];

// ── Quick links ───────────────────────────────────────────────────────────────
// Shown as tappable rows under "At a glance" on the Info tab.
const quickLinks = [
  {
    icon: '📋',
    label: 'Check guests in',
    url: 'https://docs.google.com/spreadsheets/d/1ynjh4GpLGLPZjHzHRXxhkQpvhFdj_NqHdMmzXt3Qavs/edit?usp=sharing',
  },
  { icon: '💺', label: 'Find your seat', url: 'https://may-i-seat-yu.vercel.app' },
];
